services:
  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    env_file:
      - bot/.env
    restart: unless-stopped

  tma:
    build:
      context: .
      dockerfile: tma/Dockerfile
    env_file:
      - tma/.env
    ports:
      - "3002:3000"
    restart: unless-stopped